WIP: Fix warnings in unit conversions (#1047)
wright-group/WrightTools pull request #1048
Opened 2022-02-08 20:41 UTC by darienmorrow

## Changes

Unit conversions of None to None no longer throws a warning.
Invalid unit conversions now throw a pint error.

## Checklist

- [ ] added tests, if applicable
- [ ] updated documentation, if applicable
- [ ] updated CHANGELOG.md
- [ ] tests pass

2022-02-08 20:42 UTC, darienmorrow commented
I believe this PR has the desired properties as discussed in #1047. 

@ksunden Can you test this against acquisition hardware? 

Example code showing the new behavior is as follows:
```
import WrightTools as wt
import pint

c = wt.units.converter
# fine return converted value
print(c(val=12500, current_unit='wn', destination_unit='eV'))
# fine return input
print(c(val=12500, current_unit=None, destination_unit=None))
# warning return input
print(c(val=12500, current_unit=None, destination_unit='eV'))
print(c(val=12500, current_unit='wn', destination_unit=None))
# error
try: 
    print(c(val=12500, current_unit='wn', destination_unit='W'))
except pint.errors.DimensionalityError:
    print('error thrown 1')
try:
    print(c(val=12500, current_unit='W', destination_unit='wn'))
except pint.errors.DimensionalityError:
    print('error thrown 2')
```

2022-02-22 15:09 UTC, darienmorrow commented
ping @ksunden

2022-03-09 18:26 UTC, ksunden commented on WrightTools/units.py
> +    if (current_unit == None) and (destination_unit == None):
please use `is None` instead of `== None` (this is more efficient and standard style (see code scanning results)

2022-03-09 18:31 UTC, ksunden requested changes
Implementation looks good, works fine with yaqc-cmds.

Please add tests of new behavior (your comment plus some assertions is a good place to start)

2022-03-12 21:24 UTC, darienmorrow commented
@ksunden I added tests. If all is good, please merge.

2022-03-21 20:46 UTC, ksunden commented
For future reference, @darienmorrow as much as I saw the comment originally that it was ready for review and I resolved some merge conflicts and told myself I would merge once the tests passed.... I ignored this for longer than I intended to in large part due to the WIP in the title (every time I saw it in my notifications list I was like "Oh, this must still need something")

Changing the title would have gotten my attention sooner

2022-03-21 20:46 UTC, ksunden approved these changes

2022-03-21 20:46 UTC, merged