enable compression
wright-group/WrightTools pull request #1085
Opened 2022-07-19 22:54 UTC by ksunden

## Changes

Enable passing compression/compression opts/shuffle arguments to h5py `require_dataset` 

Initially this is posted to allow testing in bluesky-in-a-box, so draft without any tests/docs added yet

## Checklist

- [ ] added tests, if applicable
- [ ] updated documentation, if applicable
- [ ] updated CHANGELOG.md
- [ ] tests pass

2022-07-19 23:47 UTC, ksunden commented on WrightTools/data/_variable.py
> +        super_kwargs = {k: kwargs[k] for k in ("compression", "shuffle") if k in kwargs}
```suggestion
```

initially thought passing kwargs here was needed, turned out only in the _data file

2022-07-19 23:49 UTC, ksunden commented
Dataset is (51, 61, 551) with array detector for the last axis, all other datasets are just 51x61

original file (without any compression): 34 MB
repacked: 29 MB
repacked and compressed: 1.8 MB

compression while collecting: 7.0 MB
repacked from compression while collecting (still compressed): 2.0 MB

2022-07-27 20:07 UTC, kameyer226 requested changes
Win10 checks out

The test script needs ability to verify data integrity between uncompressed and compressed files.

2022-07-27 20:10 UTC, untzag approved these changes

2022-07-27 20:46 UTC, ksunden commented
honestly I'm not interested in testing data integrity, that is h5py's job, which I trust them greatly to do... The test is simply proving that it is indeed applied to begin with.

2022-07-27 21:26 UTC, kameyer226 commented
ok

2022-07-27 21:26 UTC, kameyer226 approved these changes

2022-07-27 21:26 UTC, merged