Data drop method
wright-group/WrightTools pull request #1134
Opened 2023-07-07 18:57 UTC by ddkohler

## Changes

* new Data method `squeeze`, our analogue of np.squeeze
* resolves #1069 

## Checklist

- [ ] added tests, if applicable
- [ ] updated documentation, if applicable
- [ ] updated CHANGELOG.md
- [ ] tests pass

2023-08-07 20:33 UTC, kameyer226 commented on tests/data/squeeze.py
> +"""Test chop."""
-> """Test squeeze."""

2023-08-07 20:34 UTC, kameyer226 requested changes
Should be good except for the one replace.  Nice addition!

2023-08-08 18:03 UTC, ddkohler commented
This PR is still a work in progress.  Specifically, the squeezed data objects need to work on the Constant objects they create.

2024-01-30 18:54 UTC, kameyer226 approved these changes

2024-01-30 18:54 UTC, merged